PsychError: Fix error reporting for argument data types uint64/int64.
The enum values were wrong, because 2^15 etc. were mapped to double
or something, instead of the int's we wanted :/.

And int64 wasn't defined for mapping in the first place.

This fixes the error message if a int64 or uint64 is expected and
something else provided.